I found the reason for the following error:
	undefined method `cascading_name' for #<ODDB::Drugs::Sequence:0xb5080fec>

Sequence.rb (68 lines) needs to be taken from

	de.oddb.org

not from the pure

	ODDB (64 lines)

Library.